#!/bin/bash

mkdir git-repos

cd git-repos

repositories = $(curl -s https://api.github.com/users/GregorioGadea/repos | awk `/ssh_url/{print $2}` | sed `s/^"//g` | sed 
`s/",$//g`)

for repository in $repositories
do
	git clone $repository
done

